<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>annotations</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors>$(WarningsAsErrors);nullable</WarningsAsErrors>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <IsPackable>false</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>NetWasm.Microsoft.Extensions.Logging.Generators</AssemblyName>
    <RootNamespace>Microsoft.Extensions.Logging.Generators</RootNamespace>
    <DefineConstants>$(DefineConstants);ROSLYN4_0_OR_GREATER</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="*.cs" />
    <Compile Include="Common/Roslyn/*.cs" />
    <Compile Include="Common/System/ValueListBuilder.cs" />
    <Compile Include="Common/System/ValueListBuilder.Pop.cs" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
