<Project Sdk="NetWasm.Sdk">
  <PropertyGroup>
    <TargetFramework></TargetFramework>
    <TargetFrameworks>net10.0;netwasm0.1</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <TUnitSourceGenerationMode>ClosedWorldCatalog</TUnitSourceGenerationMode>
    <NoWarn>$(NoWarn);TUnit0034;TUnit0038</NoWarn>
    <DisableImplicitFrameworkReferences Condition="'$(TargetFramework)' == 'net10.0'">true</DisableImplicitFrameworkReferences>
    <NoStdLib Condition="'$(TargetFramework)' == 'net10.0'">false</NoStdLib>
    <NoStandardLibraries Condition="'$(TargetFramework)' == 'net10.0'">false</NoStandardLibraries>
    <NoCompilerStandardLib Condition="'$(TargetFramework)' == 'net10.0'">false</NoCompilerStandardLib>
    <DisableStandardFrameworkResolution Condition="'$(TargetFramework)' == 'net10.0'">true</DisableStandardFrameworkResolution>
  </PropertyGroup>

  <ItemGroup>
    <Using Remove="Xunit" />
    <PackageReference Include="NetWasm.TUnit" Version="[$(NetWasmTUnitPackageVersion)]" />
    <PackageReference Include="NetWasm.System.Linq.AsyncEnumerable"
                      Version="[$(NetWasmSystemLinqAsyncEnumerablePackageVersion)]"
                      Condition="'$(TargetFramework)' == 'netwasm0.1'" />
    <FrameworkReference Include="Microsoft.NETCore.App" Condition="'$(TargetFramework)' == 'net10.0'" />
  </ItemGroup>

</Project>
