<Project Sdk="NetWasm.Sdk">
  <PropertyGroup>
    <TargetFramework>netwasm0.1</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Microsoft.Extensions.Caching.Abstractions</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <IsPackable>true</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(DefineConstants);NET;NETWASM</DefineConstants>
    <PackageId>NetWasm.Microsoft.Extensions.Caching.Abstractions</PackageId>
    <Version>$(NetWasmMicrosoftExtensionsCachingAbstractionsPackageVersion)</Version>
    <PackageVersion>$(NetWasmMicrosoftExtensionsCachingAbstractionsPackageVersion)</PackageVersion>
    <Description>NetWasm in-process caching contracts and options.</Description>
    <PackageTags>netwasm;microsoft;extensions;caching;abstractions</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>$(NetWasmPortedLibrariesRepositoryUrl)</PackageProjectUrl>
    <RepositoryUrl>$(NetWasmPortedLibrariesRepositoryUrl)</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.cs" />
    <Compile Include="Microsoft/Extensions/Caching/**/*.cs" />
    <Compile Include="Microsoft/Extensions/Internal/*.cs" />
    <ProjectReference Include="../NetWasm.Microsoft.Extensions.Primitives/NetWasm.Microsoft.Extensions.Primitives.csproj" Condition="'$(NetWasmPackPackageGraph)' != 'true'" />
    <PackageReference Include="NetWasm.Microsoft.Extensions.Primitives" Version="[$(NetWasmMicrosoftExtensionsPrimitivesPackageVersion)]" Condition="'$(NetWasmPackPackageGraph)' == 'true'" />
    <None Update="README.md" Pack="true" PackagePath="README.md" />
  </ItemGroup>
</Project>
